### ISSUE TITLE
Create Cart button component and add it to Header

### ISSUE THREAD

**Issue by IrvingWash** [samhainsamhainsamhain/tsreactmarketplace#10]
Создать и стилизовать кнопку открытия корзины, в которой будет, например слово "корзина", счётчик количества всех добавленных товаров, счётчик цены всех добавленных товаров.

Писать логику для счётчиков не нужно (не надо чтобы они сейчас работали). 

Интерфейс самой корзины тоже пока не нужно делать

**Comment by samhainsamhainsamhain** [comment]
Кнопка Корзины была добавлена вместе с коммитом Header-component
